---
- hosts: 192.168.2.33
  tasks:
   - name: create folder to store list of updates
     file:
       path: C:\ppms\packagelist
       state: directory  
   
   - name: Retrieve list of updates from Windows and update to ppms folder
     win_updates:
       category_names:
         - Updates
         - CriticalUpdates
         - SecurityUpdates
         - UpdateRollups
       state: searched
       log_path: C:\ppms\packagelist.txt
     register: result
